name: Package cosmotech-business-webapp chart

on:
  push:
    tags:
      - 'cosmotech-business-webapp-chart-*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4

      - name: Helm lint
        working-directory: webapp_server/charts/cosmotech-business-webapp
        run: |
          helm lint --strict .

      - name: Helm package
        working-directory: webapp_server/charts/cosmotech-business-webapp
        run: |
          helm package .

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            helm registry login ghcr.io \
              --username "${{ github.actor }}" \
              --password-stdin

      - name: Helm push
        working-directory: webapp_server/charts/cosmotech-business-webapp
        run: |
          helm push cosmotech-business-webapp-*.tgz oci://ghcr.io/cosmo-tech
